Magic_Villa_Web/Controllers/VillaController.cs
using AutoMapper;
using Magic_Villa_Web.Models;
using Magic_Villa_Web.Models.Dto.VillaDto;
using Magic_Villa_Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using System.Text.Json;
namespace Magic_Villa_Web.Controllers
{
    public class VillaController : Controller
    {
        public IVillaServices VillaServices { get; }
        public IMapper Mapper { get; }
        public VillaController(IVillaServices villaServices, IMapper mapper)
        {
            VillaServices = villaServices;
            Mapper = mapper;
        }


        public async Task<IActionResult> Index()
        {
            var response = await VillaServices.GetAllAsync<ApiResponse>();
            if (response != null && response.IsSuccess)
            {
                var resultString = response.Result.ToString();
                var villas = JsonSerializer.Deserialize<List<VillaDto>>(
                    resultString,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );

                //foreach (var villa in villas)
                //{
                //    Console.WriteLine($"Villa: {villa.Name}, ID: {villa.Id}");
                //}

                return View(villas);
            }
            return View(new List<VillaDto>());
        }
        public async Task<IActionResult> Create()
        {
            return View();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VillaCreateDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await VillaServices.CreateAsync<ApiResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
            }

            return View(model);
        }

        [HttpGet]
        public async Task<IActionResult> Update(int id)
        {
            var response = await VillaServices.GetByIdAsync<ApiResponse>(id);
            if (response != null && response.IsSuccess)
            {
                var resultString = response.Result.ToString();
                var villaDto = JsonSerializer.Deserialize<VillaDto>(
                    resultString,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );
                return View(Mapper.Map<VillaUpdateDto>(villaDto));
            }
            return NotFound();
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Update(VillaUpdateDto model)
        {
            if (ModelState.IsValid)
            {
                var response = await VillaServices.UpdateAsync<ApiResponse>(model);
                if (response != null && response.IsSuccess)
                {
                    return RedirectToAction(nameof(Index));
                }
            }
            return View(model);
        }
        
        public async Task<IActionResult> Delete(int id)
        {
            var response = await VillaServices.GetByIdAsync<ApiResponse>(id);
            if (response != null && response.IsSuccess)
            {
                var resultString = response.Result.ToString();
                var villaDto = JsonSerializer.Deserialize<VillaDto>(
                    resultString,
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );
                return View(villaDto);
            }
            return NotFound();
        }
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Delete(VillaDto model)
        {
            var response = await VillaServices.DeleteAsync<ApiResponse>(model.Id);

            if (response != null && response.IsSuccess)
            {
                TempData["success"] = "Villa deleted successfully";
                return RedirectToAction(nameof(Index));
            }
            return RedirectToAction(nameof(Index));
        }
    }
}

Magic_Villa_Web/Controllers/VillaNumberController.cs
using AutoMapper;
using Magic_Villa_Web.Model.ViewModel;
using Magic_Villa_Web.Models;
using Magic_Villa_Web.Models.Dto.VillaDto;
using Magic_Villa_Web.Models.Dto.VillaNumberDto;
using Magic_Villa_Web.Services.IServices;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using System.Text.Json;

namespace Magic_Villa_Web.Controllers
{
    public class VillaNumberController : Controller
    {
        private readonly IVillaNumberServices _villaNumberServices;
        private readonly IMapper _mapper;
        private readonly IVillaServices _villaServices;

        public VillaNumberController(
            IVillaNumberServices villaNumberServices,
            IVillaServices villaServices,
            IMapper mapper)
        {
            _villaNumberServices = villaNumberServices;
            _villaServices = villaServices;
            _mapper = mapper;
        }

        public async Task<IActionResult> Index()
        {
            List<VillaNumberDto> list = new();

            var response = await _villaNumberServices.GetAllAsync<ApiResponse>();
            if (response != null && response.IsSuccess && response.Result != null)
            {
                list = JsonSerializer.Deserialize<List<VillaNumberDto>>(
                    ((JsonElement)response.Result).GetRawText(),
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );
            }

            return View(list);
        }

        [HttpGet]
        public async Task<IActionResult> Create()
        {
            var villaNumberCreateVM = new VillaNumberCreateVM();

            var response = await _villaServices.GetAllAsync<ApiResponse>();

            if (response != null && response.IsSuccess && response.Result != null)
            {
                var villas = JsonSerializer.Deserialize<List<VillaDto>>(
                    ((JsonElement)response.Result).GetRawText(),
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );

                villaNumberCreateVM.VillaList = villas.Select(v => new SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                }).ToList();
            }

            return View(villaNumberCreateVM);
        }

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create(VillaNumberCreateVM model)
        {
            if (ModelState.IsValid)
            {
                var response = await _villaNumberServices
                    .CreateAsync<ApiResponse>(model.villaNumber);

                if (response != null && response.IsSuccess)
                {
                    TempData["success"] = "Villa Number created successfully";
                    return RedirectToAction(nameof(Index));
                }
                else
                {
                    if (response?.ErrorMessage != null )
                    {
                        ModelState.AddModelError("", response.ErrorMessage);
                    }
                }
            }


            var villaResponse = await _villaServices.GetAllAsync<ApiResponse>();

            if (villaResponse != null && villaResponse.IsSuccess && villaResponse.Result != null)
            {
                var villas = JsonSerializer.Deserialize<List<VillaDto>>(
                    ((JsonElement)villaResponse.Result).GetRawText(),
                    new JsonSerializerOptions { PropertyNameCaseInsensitive = true }
                );

                model.VillaList = villas.Select(v => new SelectListItem
                {
                    Text = v.Name,
                    Value = v.Id.ToString()
                }).ToList();
            }

            return View(model);
        }
    }
}

Magic_Villa_Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Magic_Villa_Web</title>
    <script type="importmap"></script>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" asp-append-version="true" />
    <link rel="stylesheet" href="~/Magic_Villa_Web.styles.css" asp-append-version="true" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container-fluid">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Magic_Villa_Web</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Villa" asp-action="index">Villa List</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="VillaNumber" asp-action="index">VillaNumber</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2025 - Magic_Villa_Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>